log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ "Clock", "Tray", "Updates", "appLauncher", "WindowTitle" ]
center = [ "Workspaces", "Privacy" ]
right = [ "MediaPlayer", "Settings", "SystemInfo", ["kernelVersion", "hyprlandVersion"], "notifications" ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "MonitorSpecificExclusive"
enable_workspace_filling = false
disable_special_workspaces = true

[clock]
format = "%d | %I:%M %p"

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "walker"

[[CustomModule]]
name = "notifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[[CustomModule]]
name = "kernelVersion"
icon = ""
command = "sh ./kernel_version.sh"
listen_cmd = "sh ./kernel_version.sh"


[[CustomModule]]
name = "hyprlandVersion"
icon = ""
command = "sh ./hyprland_version.sh"
listen_cmd = "sh ./hyprland_version.sh"

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
style = "Islands"

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7" ] #, "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7" ] #, "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
